In [1]:
from pyspark.sql import Row
from pyspark.sql import SQLContext
from datetime import datetime as dt
import pandas as pd
sqlContext = SQLContext(sc)

In [2]:
#sc = SparkContext(master='local', appName='AmadeusClstr')
bFile = "bookings.csv"
sFile = "searches.csv"
bookingFile = sc.textFile(bFile)
searchesFile = sc.textFile(sFile)

### First exercise: count the number of lines in Python for each file

In [2]:
print("# of lines for bookings.csv : " + str(bookingFile.count()))
print("# of lines for searches.csv : " + str(searchesFile.count()))

# of lines for bookings.csv : 10000011
# of lines for searches.csv : 20390199

### Second exercise: top 10 arrival airports in the world in 2013

In [4]:
# I have statically set columns indexes of arr_port and pax 
def trimText(obj):
    for idx, val in enumerate(obj):
        obj[idx] = str(val).strip()
    return obj

dfBookings = bookingFile.map(lambda l: l.split("^")).map(trimText)
header = dfBookings.first() #extract header
dfBookings = dfBookings.filter(lambda x :  x != header).map(lambda x : (str(x[12]), int(x[34])))

In [5]:
dfBookings.take(10)

[('LHR', -1),
 ('CLT', 1),
 ('CLT', 1),
 ('SVO', 1),
 ('SVO', 1),
 ('LGA', 1),
 ('LGA', 1),
 ('SIN', 2),
 ('SIN', 2),
 ('SIN', 2)]

In [6]:
def sumBookings(myList):
    ssum = 0
    for idx, val in enumerate(myList):
        ssum = ssum + val[1]
    return ssum

bookingsAiportGrouped = dfBookings.groupBy(lambda tup: tup[0]).map(lambda x: (x[0], len(list(x[1]))))

In [7]:
# TODO :  it gets "IndexError: list index out of range"
bookingsAiportGrouped.take(5)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 63 in stage 3.0 failed 1 times, most recent failure: Lost task 63.0 in stage 3.0 (TID 66, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 2423, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 2423, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 346, in func
    return f(iterator)
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 1926, in combine
    merger.mergeValues(iterator)
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\shuffle.py", line 236, in mergeValues
    for k, v in iterator:
  File "<ipython-input-4-f37183f42a38>", line 9, in <lambda>
IndexError: list index out of range

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:395)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:446)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 2423, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 2423, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 346, in func
    return f(iterator)
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\pyspark\rdd.py", line 1926, in combine
    merger.mergeValues(iterator)
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\shuffle.py", line 236, in mergeValues
    for k, v in iterator:
  File "<ipython-input-4-f37183f42a38>", line 9, in <lambda>
IndexError: list index out of range

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:395)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

In [8]:
# TODO : Same error with spark DataFrame : IndexError: list index out of range
dff = dfBookings.toDF(["arr_port", "pax"])
aka = dff.groupBy("arr_port").agg({"pax":"sum"})
aka.take(5)

Py4JJavaError: An error occurred while calling o182.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 63 in stage 6.0 failed 1 times, most recent failure: Lost task 63.0 in stage 6.0 (TID 133, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "<ipython-input-4-f37183f42a38>", line 9, in <lambda>
IndexError: list index out of range

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:156)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:152)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:336)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply$mcI$sp(Dataset.scala:2803)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:2800)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:2800)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2823)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:2800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\opt\spark\spark-2.2.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "<ipython-input-4-f37183f42a38>", line 9, in <lambda>
IndexError: list index out of range

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:156)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:152)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

In [11]:
import pandas as pd
pd.set_option('display.max_columns', None)
bookingsDF = pd.read_csv(bFile, nrows=50, sep="^")

In [12]:
bookingsDF

,act_date,source,pos_ctry,pos_iata,pos_oid,rloc,cre_date,duration,distance,dep_port,dep_city,dep_ctry,arr_port,arr_city,arr_ctry,lst_port,lst_city,lst_ctry,brd_port,brd_city,brd_ctry,off_port,off_city,off_ctry,mkt_port,mkt_city,mkt_ctry,intl,route,carrier,bkg_class,cab_class,brd_time,off_time,pax,year,month,oid
0,2013-03-05 00:00:00,1A,DE,a68dd7ae953c8acfb187a1af2dcbe123,1a11ae49fcbf545fd2afc1a24d88d2b7,ea65900e72d71f4626378e2ebd298267,2013-02-22 00:00:00,1708,0,ZRH,ZRH,CH,LHR,LON,GB,ZRH,ZRH,CH,LHR,LON,GB,ZRH,ZRH,CH,LHRZRH,LONZRH,CHGB,1,LHRZRH,VI,T,Y,2013-03-07 08:50:00,2013-03-07 11:33:37,-1,2013,3,NULL
1,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,SAL,SV,CLT,CLT,US,SAL,SAL,SV,SAL,SAL,SV,CLT,CLT,US,CLTSAL,CLTSAL,SVUS,1,SALATLCLT,NV,L,Y,2013-04-12 13:04:00,2013-04-12 22:05:40,1,2013,3,NULL
2,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,SAL,SV,CLT,CLT,US,SAL,SAL,SV,CLT,CLT,US,SAL,SAL,SV,CLTSAL,CLTSAL,SVUS,1,CLTATLSAL,NV,U,Y,2013-07-15 07:00:00,2013-07-15 11:34:51,1,2013,3,NULL
3,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,AKL,NZ,SVO,MOW,RU,AKL,AKL,NZ,AKL,AKL,NZ,SVO,MOW,RU,AKLSVO,AKLMOW,NZRU,1,AKLHKGSVO,XK,G,Y,2013-04-24 23:59:00,2013-04-25 16:06:31,1,2013,3,SYDA82546
4,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,AKL,NZ,SVO,MOW,RU,AKL,AKL,NZ,SVO,MOW,RU,AKL,AKL,NZ,AKLSVO,AKLMOW,NZRU,1,SVOHKGAKL,XK,G,Y,2013-05-14 20:15:00,2013-05-16 10:44:50,1,2013,3,SYDA82546
5,2013-03-20 00:00:00,1V,US,0283592e45e392871f7e14b1e22a9aaf,2d0f8e7e1bb792625d2f34f221bc38f1,d54708298686de200f8270e7c637af5e,2013-03-20 00:00:00,5923,0,DEN,DEN,US,LGA,NYC,US,DEN,DEN,US,DEN,DEN,US,LGA,NYC,US,DENLGA,DENNYC,USUS,0,DENLGA,FK,W,Y,2013-04-07 10:23:00,2013-04-07 16:14:24,1,2013,3,NULL
6,2013-03-20 00:00:00,1V,US,0283592e45e392871f7e14b1e22a9aaf,2d0f8e7e1bb792625d2f34f221bc38f1,d54708298686de200f8270e7c637af5e,2013-03-20 00:00:00,5923,0,DEN,DEN,US,LGA,NYC,US,DEN,DEN,US,LGA,NYC,US,DEN,DEN,US,DENLGA,DENNYC,USUS,0,LGADEN,FK,K,Y,2013-04-11 11:15:00,2013-04-11 13:06:24,1,2013,3,NULL
7,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,NRT,TYO,JP,SIN,SIN,SG,NRTSIN,SINTYO,JPSG,1,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,2,2013,3,NULL
8,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,SIN,SIN,SG,PEN,PEN,MY,PENSIN,PENSIN,MYSG,1,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,2,2013,3,NULL
9,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,PEN,PEN,MY,BKK,BKK,TH,BKKPEN,BKKPEN,MYTH,1,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,2,2013,3,NULL
10,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,BKK,BKK,TH,HND,TYO,JP,BKKHND,BKKTYO,JPTH,1,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,2,2013,3,NULL
11,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,NRT,TYO,JP,SIN,SIN,SG,NRTSIN,SINTYO,JPSG,1,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,-2,2013,3,NULL
12,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,SIN,SIN,SG,PEN,PEN,MY,PENSIN,PENSIN,MYSG,1,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,-2,2013,3,NULL
13,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,PEN,PEN,MY,BKK,BKK,TH,BKKPEN,BKKPEN,MYTH,1,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,-2,2013,3,NULL
14,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,BKK,BKK,TH,HND,TYO,JP,BKKHND,BKKTYO,JPTH,1,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,-2,2013,3,NULL
15,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,NRT,TYO,JP,SIN,SIN,SG,NRTSIN,SINTYO,JPSG,1,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,1,2013,3,NULL
16,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,SIN,SIN,SG,PEN,PEN,MY,PENSIN,PENSIN,MYSG,1,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,1,2013,3,NULL
17,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,PEN,PEN,MY,BKK,BKK,TH,BKKPEN,BKKPEN,MYTH,1,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,1,2013,3,NULL
18,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,SIN,SIN,SG,HND,TYO,JP,BKK,BKK,TH,HND,TYO,JP,BKKHND,BKKTYO,JPTH,1,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,1,2013,3,NULL
19,2013-03-13 00:00:00,1V,CA,f8d15f8b5e04f0cfcb62f299d059beb3,257170d899c9dc7744a83f18c399bc1c,c302645256976e555e80bc46a3f982d7,2013-03-13 00:00:00,11640,0,YYZ,YTO,CA,TUS,TUS,US,YYZ,YTO,CA,YYZ,YTO,CA,TUS,TUS,US,TUSYYZ,TUSYTO,CAUS,1,YYZTUS,FK,V,Y,2013-04-06 13:28:00,2013-04-06 14:48:17,1,2013,3,NULL
20,2013-03-25 00:00:00,1A,IT,f1c9acf55eb44dedd43734952a9138a6,7f3988fed8c1fe28c882eb979acc046c,57af3d59571623b706c04ac178d5900b,2013-03-12 00:00:00,9240,0,FCO,ROM,IT,CTA,CTA,IT,FCO,ROM,IT,FCO,ROM,IT,CTA,CTA,IT,CTAFCO,CTAROM,ITIT,0,FCOCTA,KK,O,Y,2013-05-25 07:25:00,2013-05-25 08:50:57,-2,2013,3,NULL
21,2013-03-25 00:00:00,1A,IT,f1c9acf55eb44dedd43734952a9138a6,7f3988fed8c1fe28c882eb979acc046c,57af3d59571623b706c04ac178d5900b,2013-03-12 00:00:00,9175,0,FCO,ROM,IT,CTA,CTA,IT,FCO,ROM,IT,FCO,ROM,IT,CTA,CTA,IT,CTAFCO,CTAROM,ITIT,0,FCOCTA,KK,O,Y,2013-05-25 08:30:00,2013-05-25 09:55:57,2,2013,3,NULL
22,2013-03-12 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,BDQ,BDQ,IN,YWG,YWG,CA,BDQYWG,BDQYWG,CAIN,1,BDQDELYYZYWG,CH,N,Y,2013-03-24 20:50:00,2013-03-25 19:34:05,2,2013,3,BDQAK3101
23,2013-03-12 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,YWG,YWG,CA,AMD,AMD,IN,AMDYWG,AMDYWG,CAIN,1,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-05 12:35:00,2013-08-07 05:59:19,2,2013,3,BDQAK3101
24,2013-03-13 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,YWG,YWG,CA,AMD,AMD,IN,AMDYWG,AMDYWG,CAIN,1,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-05 12:35:00,2013-08-07 05:59:19,-2,2013,3,BDQAK3101
25,2013-03-13 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219429,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,YWG,YWG,CA,AMD,AMD,IN,AMDYWG,AMDYWG,CAIN,1,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-22 10:35:00,2013-08-24 05:59:19,2,2013,3,BDQAK3101
26,2013-03-18 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,BDQ,BDQ,IN,DEL,DEL,IN,BDQDEL,BDQDEL,ININ,0,BDQBOMDEL,CH,T,Y,2013-03-24 19:15:00,2013-03-25 04:33:17,2,2013,3,BDQAK3101
27,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,BDQ,BDQ,IN,DEL,DEL,IN,BDQDEL,BDQDEL,ININ,0,BDQBOMDEL,CH,T,Y,2013-03-24 19:15:00,2013-03-25 04:33:17,-2,2013,3,BDQAK3101
28,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,BDQ,BDQ,IN,YWG,YWG,CA,BDQYWG,BDQYWG,CAIN,1,BDQDELYYZYWG,CH,N,Y,2013-03-24 20:50:00,2013-03-25 19:34:05,-2,2013,3,BDQAK3101
29,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,BDQ,IN,YWG,YWG,CA,AMD,AMD,IN,BDQ,BDQ,IN,YWG,YWG,CA,BDQYWG,BDQYWG,CAIN,1,BDQBOMBRUYYZYWG,CH,U,Y,2013-03-24 19:15:00,2013-03-25 19:34:05,2,2013,3,BDQAK3101
30,2013-03-12 00:00:00,1A,FR,72ed20ddb69598dd472db8701a58a721,38a3abb0a28e3f00fa79a11f552a5052,7b948bad4978da6b181464d764a135e6,2013-03-12 00:00:00,18698,0,CDG,PAR,FR,PVG,SHA,CN,CDG,PAR,FR,CDG,PAR,FR,PVG,SHA,CN,CDGPVG,PARSHA,CNFR,1,CDGZRHPVG,VI,W,Y,2013-03-18 09:50:00,2013-03-19 07:30:06,2,2013,3,PARED38AA
31,2013-03-12 00:00:00,1A,FR,72ed20ddb69598dd472db8701a58a721,38a3abb0a28e3f00fa79a11f552a5052,7b948bad4978da6b181464d764a135e6,2013-03-12 00:00:00,18698,0,CDG,PAR,FR,PVG,SHA,CN,CDG,PAR,FR,PVG,SHA,CN,CPH,CPH,DK,CPHPVG,CPHSHA,CNDK,1,PVGCPH,DU,T,Y,2013-03-30 14:05:00,2013-03-30 17:36:54,2,2013,3,PARED38AA
32,2013-03-12 00:00:00,1A,FR,72ed20ddb69598dd472db8701a58a721,38a3abb0a28e3f00fa79a11f552a5052,7b948bad4978da6b181464d764a135e6,2013-03-12 00:00:00,18698,0,CDG,PAR,FR,PVG,SHA,CN,CDG,PAR,FR,CPH,CPH,DK,CDG,PAR,FR,CDGCPH,CPHPAR,DKFR,1,CPHCDG,DU,T,Y,2013-03-31 08:30:00,2013-03-31 10:28:48,2,2013,3,PARED38AA
33,2013-03-12 00:00:00,1A,UA,a780825254ef5706f1ab2d026abb7cd0,34f865916f67014ecd1aea4c3cafc87d,0ce36224872a9809fcac5939cbe440db,2013-03-12 00:00:00,743,3114,SIP,SIP,UA,SGC,SGC,RU,SGC,SGC,RU,SIP,SIP,UA,SGC,SGC,RU,SGCSIP,SGCSIP,RUUA,1,SIPSVOSGC,DF,E,Y,2013-03-19 12:00:00,2013-03-20 04:23:35,1,2013,3,SIPU23503
34,2013-03-12 00:00:00,1A,IT,af34a799f696cdf3e0ce94b08f85065d,420d4e097328072d82d09db39f61764d,7a1da5f4414531264818d2546bfb3973,2013-03-12 00:00:00,7281,0,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,LIN,MIL,IT,ALG,ALG,DZ,ALGLIN,ALGMIL,DZIT,1,LINFCOALG,KK,T,Y,2013-04-08 08:00:00,2013-04-08 11:10:53,1,2013,3,NULL
35,2013-03-12 00:00:00,1A,IT,af34a799f696cdf3e0ce94b08f85065d,420d4e097328072d82d09db39f61764d,7a1da5f4414531264818d2546bfb3973,2013-03-12 00:00:00,7281,0,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,ALGLIN,ALGMIL,DZIT,1,ALGFCOLIN,KK,O,Y,2013-04-13 03:20:00,2013-04-13 09:21:15,1,2013,3,NULL
36,2013-03-14 00:00:00,1A,IT,af34a799f696cdf3e0ce94b08f85065d,420d4e097328072d82d09db39f61764d,7a1da5f4414531264818d2546bfb3973,2013-03-12 00:00:00,7281,0,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,LIN,MIL,IT,ALG,ALG,DZ,ALGLIN,ALGMIL,DZIT,1,LINFCOALG,KK,T,Y,2013-04-08 08:00:00,2013-04-08 11:10:53,-1,2013,3,NULL
37,2013-03-14 00:00:00,1A,IT,af34a799f696cdf3e0ce94b08f85065d,420d4e097328072d82d09db39f61764d,7a1da5f4414531264818d2546bfb3973,2013-03-12 00:00:00,7281,0,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,ALG,ALG,DZ,LIN,MIL,IT,ALGLIN,ALGMIL,DZIT,1,ALGFCOLIN,KK,O,Y,2013-04-13 03:20:00,2013-04-13 09:21:15,-1,2013,3,NULL
38,2013-03-12 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DEL,DEL,IN,DMM,DMM,SA,DELDMM,DELDMM,INSA,1,DELDMM,KS,Q,Y,2013-03-14 01:00:00,2013-03-14 02:28:15,2,2013,3,NULL
39,2013-03-12 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DELDMM,DELDMM,INSA,1,DMMDEL,KS,Q,Y,2013-04-09 03:40:00,2013-04-09 10:08:15,2,2013,3,NULL
40,2013-03-13 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DEL,DEL,IN,DMM,DMM,SA,DELDMM,DELDMM,INSA,1,DELDMM,KS,Q,Y,2013-03-14 01:00:00,2013-03-14 02:28:15,-2,2013,3,NULL
41,2013-03-13 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DELDMM,DELDMM,INSA,1,DMMDEL,KS,Q,Y,2013-04-09 03:40:00,2013-04-09 10:08:15,-2,2013,3,NULL
42,2013-03-13 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DEL,DEL,IN,DMM,DMM,SA,DELDMM,DELDMM,INSA,1,DELDMM,KS,Q,Y,2013-03-14 01:00:00,2013-03-14 02:28:15,1,2013,3,NULL
43,2013-03-13 00:00:00,1A,IN,a171b04cbc52803b9380311815be83eb,a1b06dc7ea4426040104f5b1394db502,b41711e029cd18b987d95c7daff5f2f7,2013-03-12 00:00:00,37988,0,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DMM,DMM,SA,DEL,DEL,IN,DELDMM,DELDMM,INSA,1,DMMDEL,KS,Q,Y,2013-04-09 03:40:00,2013-04-09 10:08:15,1,2013,3,NULL
44,2013-03-12 00:00:00,1A,RU,4fecb6ea5afb51ba32e2033a548f30f0,7326b849b91e49d5b597213f0c308392,c0aeb3ac3fdf47735ea3a4cfb462c9b2,2013-03-12 00:00:00,186,1957,SOF,SOF,BG,LED,LED,RU,LED,LED,RU,SOF,SOF,BG,LED,LED,RU,LEDSOF,LEDSOF,BGRU,1,SOFLED,PG,W,Y,2013-03-23 10:00:00,2013-03-23 15:06:09,1,2013,3,NULL
45,2013-03-27 00:00:00,1A,PT,fe865f9d8c1f23eba1647744c5467378,a1d2d5359a55cc2617c9a86ae0b8a379,6ae8f9f359ed708b0758e53c7d1bbba4,2013-03-27 00:00:00,40674,0,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,ORY,PAR,FR,LIS,LIS,PT,LISORY,LISPAR,FRPT,1,ORYLIS,KS,L,Y,2013-05-05 15:50:00,2013-05-05 17:19:23,2,2013,3,NULL
46,2013-03-27 00:00:00,1A,PT,fe865f9d8c1f23eba1647744c5467378,a1d2d5359a55cc2617c9a86ae0b8a379,6ae8f9f359ed708b0758e53c7d1bbba4,2013-03-27 00:00:00,40674,0,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LISORY,LISPAR,FRPT,1,LISORY,KS,V,Y,2013-06-02 18:15:00,2013-06-02 21:44:23,2,2013,3,NULL
47,2013-03-28 00:00:00,1A,PT,fe865f9d8c1f23eba1647744c5467378,a1d2d5359a55cc2617c9a86ae0b8a379,6ae8f9f359ed708b0758e53c7d1bbba4,2013-03-27 00:00:00,40674,0,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LISORY,LISPAR,FRPT,1,LISORY,KS,V,Y,2013-06-02 18:15:00,2013-06-02 21:44:23,-2,2013,3,NULL
48,2013-03-28 00:00:00,1A,PT,fe865f9d8c1f23eba1647744c5467378,a1d2d5359a55cc2617c9a86ae0b8a379,6ae8f9f359ed708b0758e53c7d1bbba4,2013-03-27 00:00:00,38724,0,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LIS,LIS,PT,ORY,PAR,FR,LISORY,LISPAR,FRPT,1,LISORY,KS,U,Y,2013-06-01 09:45:00,2013-06-01 13:14:23,2,2013,3,NULL
49,2013-03-12 00:00:00,1A,IL,27367036d7623099aa6e0eee8342109d,b9362dea7b8617a74224f37bea948446,8ef7d6c177b6bd6aadcb1acabeec2bd3,2013-03-12 00:00:00,20338,0,TLV,TLV,IL,BLR,BLR,IN,TLV,TLV,IL,TLV,TLV,IL,BLR,BLR,IN,BLRTLV,BLRTLV,ILIN,1,TLVBKKBLR,VJ,H,Y,2013-04-01 23:05:00,2013-04-02 23:33:47,1,2013,3,TLVI32729

##### Bonus point: Solve this problem using pandas (instead of any other approach)

In [40]:
chunks = pd.read_csv(bFile, sep="^", chunksize=1000000, usecols=[12, 34])
pieces = [chk.groupby('arr_port', sort=False)['pax'].agg(['sum']) for chk in chunks]
agg = pd.concat(pieces).groupby(level=0).sum()

In [41]:
agg.sort_values('sum', ascending=False).head(10)

              sum
arr_port
LHR       88809.0
MCO       70930.0
LAX       70530.0
LAS       69630.0
JFK       66270.0
CDG       64490.0
BKK       59460.0
MIA       58150.0
SFO       58000.0
DXB       55590.0